# Generated by Django 5.1 on 2024-08-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'verbose_name_plural': 'Stock History'},
        ),
    ]
