# Generated by Django 5.1 on 2024-08-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name_plural': 'Purchase History'},
        ),
    ]
