# Generated by Django 5.1 on 2024-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_purchasehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled')], default='completed', max_length=20),
        ),
    ]
