# Generated by Django 5.1 on 2024-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_purchasehistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='status',
        ),
    ]
